name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Pozwala odpalać build ręcznie

jobs:
  build:
    runs-on: windows-latest  # Budujemy na Windowsie, żeby dostać .exe

    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4  # Najnowsza wersja checkout

      - name: Instalacja Node.js
        uses: actions/setup-node@v4  # Najnowsza wersja setup-node
        with:
          node-version: 18  # Możesz sprawdzić, jaka wersja działa w repo

      - name: Instalacja zależności
        run: npm install

      - name: Budowanie aplikacji
        run: npm run dist  # Może być "npm run build" – sprawdź w package.json

      - name: Przechowywanie artefaktów
        uses: actions/upload-artifact@v4  # Używamy nowej wersji v4
        with:
          name: testownik-windows
          path: dist/*.exe  # Sprawdź, gdzie Electron generuje plik .exe
